# Name for your workflow (shows up in GitHub Actions tab)
name: Check uHomes Prices

# When this workflow should run
on:
  # Allows you to run it manually from the Actions tab on GitHub
  workflow_dispatch:
  # Defines the schedule
  schedule:
    # Runs at 9:00 AM UTC every day.
    # Use https://crontab.guru/ to create your desired schedule.
    # Format: 'Minute Hour DayOfMonth Month DayOfWeek'
    - cron: '0 9 * * *'

# Defines the tasks (jobs) to run
jobs:
  scrape-and-commit: # Name of the job
    # The type of machine to run the job on
    runs-on: ubuntu-latest

    # The sequence of steps to perform
    steps:
      # 1. Checks out your repository code onto the runner
      - name: Check out repository
        uses: actions/checkout@v4

      # 2. Sets up Python environment
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Or your preferred version

      # 3. Installs Python libraries from your requirements file
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Installs Playwright browsers & their OS dependencies
      - name: Install Playwright browsers
        run: playwright install --with-deps # '--with-deps' is important!

      # 5. Runs your actual price tracker script
      - name: Run the tracker script
        run: python price_tracker.py

      # 6. Commits and pushes any changed files (like JSON/log) back
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          # Check if there are changes (git status --porcelain)
          if [ -n "$(git status --porcelain)" ]; then
            git add uhomes_prices.json discounts.log # Add ALL files you want saved
            git commit -m "Automated price check results - $(date -u)"
            git push
          else
            echo "No changes detected to commit."
          fi